#! /bin/bash

echo "Migrating supabase..."
supabase migration up

echo "Migrating supabase remote schema..."
supabase migration up --linked

echo "Updating types..."
supabase gen types typescript --local > supabase/functions/_lib/database.types.ts
supabase gen types typescript --local > types/database.ts

echo "Done!"
